-- ==========================================================
-- crwn.st MySQL Database Schema
-- Matches ER Diagram: ERD-070969
-- ==========================================================

CREATE DATABASE IF NOT EXISTS crwn_store CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE crwn_store;

SET FOREIGN_KEY_CHECKS = 0;

-- 1. CUSTOMER
DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (
  CUS_ID VARCHAR(36) NOT NULL,
  CUS_FName VARCHAR(100) NOT NULL,
  CUS_LName VARCHAR(100) NOT NULL,
  CUS_Email VARCHAR(150) NULL,
  CUS_Tel VARCHAR(20) NOT NULL UNIQUE,
  CUS_Pass VARCHAR(100) NULL,
  PRIMARY KEY (CUS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. EMPLOYEE
DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE (
  EMP_ID VARCHAR(36) NOT NULL,
  EMP_FName VARCHAR(100) NOT NULL,
  EMP_LName VARCHAR(100) NOT NULL,
  EMP_Tel VARCHAR(20) NULL,
  EMP_Email VARCHAR(150) NULL,
  EMP_Pass VARCHAR(100) NOT NULL,
  EMP_Role VARCHAR(50) NOT NULL,
  PRIMARY KEY (EMP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. FITTING_ROOM
DROP TABLE IF EXISTS FITTING_ROOM;
CREATE TABLE FITTING_ROOM (
  FTR_Num VARCHAR(20) NOT NULL,
  FTR_Status VARCHAR(50) NOT NULL DEFAULT 'available',
  PRIMARY KEY (FTR_Num)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. FITTING_SESSION
DROP TABLE IF EXISTS FITTING_SESSION;
CREATE TABLE FITTING_SESSION (
  FTS_ID VARCHAR(36) NOT NULL,
  FTR_NUM VARCHAR(20) NOT NULL,
  CUS_ID VARCHAR(36) NULL,
  FTS_DateTime DATETIME NOT NULL,
  PRIMARY KEY (FTS_ID),
  INDEX idx_fts_room (FTR_NUM),
  INDEX idx_fts_cus (CUS_ID),
  CONSTRAINT fk_fts_room FOREIGN KEY (FTR_NUM) REFERENCES FITTING_ROOM (FTR_Num) ON DELETE CASCADE,
  CONSTRAINT fk_fts_cus FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER (CUS_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. PAY_CART
DROP TABLE IF EXISTS PAY_CART;
CREATE TABLE PAY_CART (
  PAY_CART_ID VARCHAR(36) NOT NULL,
  CUS_ID VARCHAR(36) NULL,
  PRIMARY KEY (PAY_CART_ID),
  INDEX idx_pc_cus (CUS_ID),
  CONSTRAINT fk_pc_cus FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER (CUS_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. FIT_CART
DROP TABLE IF EXISTS FIT_CART;
CREATE TABLE FIT_CART (
  FIT_CART_ID VARCHAR(36) NOT NULL,
  FTS_ID VARCHAR(36) NOT NULL,
  PAY_CART_ID VARCHAR(36) NULL,
  PRIMARY KEY (FIT_CART_ID),
  INDEX idx_fc_session (FTS_ID),
  INDEX idx_fc_paycart (PAY_CART_ID),
  CONSTRAINT fk_fc_session FOREIGN KEY (FTS_ID) REFERENCES FITTING_SESSION (FTS_ID) ON DELETE CASCADE,
  CONSTRAINT fk_fc_paycart FOREIGN KEY (PAY_CART_ID) REFERENCES PAY_CART (PAY_CART_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 7. LOCATION
DROP TABLE IF EXISTS LOCATION;
CREATE TABLE LOCATION (
  LOC_ID VARCHAR(36) NOT NULL,
  LOC_Zone VARCHAR(50) NULL,
  LOC_Lock VARCHAR(50) NULL,
  LOC_Shelf VARCHAR(50) NULL,
  LOC_Label VARCHAR(100) NULL,
  PRIMARY KEY (LOC_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 8. ITEM
DROP TABLE IF EXISTS ITEM;
CREATE TABLE ITEM (
  ITM_ID VARCHAR(36) NOT NULL,
  ITM_Name VARCHAR(150) NOT NULL,
  ITM_Description TEXT NULL,
  ITM_Price DECIMAL(10,2) NOT NULL,
  ITM_Category VARCHAR(100) NULL,
  ITM_Tag VARCHAR(200) NULL,
  ITM_Image TEXT NULL,
  PRIMARY KEY (ITM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 9. ITEM_VARIANT
DROP TABLE IF EXISTS ITEM_VARIANT;
CREATE TABLE ITEM_VARIANT (
  ITV_SKUID VARCHAR(50) NOT NULL,
  ITM_ID VARCHAR(36) NOT NULL,
  ITV_Color VARCHAR(50) NULL,
  ITV_Size VARCHAR(20) NULL,
  ITV_Stock INT NOT NULL DEFAULT 0,
  LOC_ID VARCHAR(36) NULL,
  PRIMARY KEY (ITV_SKUID),
  INDEX idx_itv_item (ITM_ID),
  INDEX idx_itv_loc (LOC_ID),
  CONSTRAINT fk_itv_item FOREIGN KEY (ITM_ID) REFERENCES ITEM (ITM_ID) ON DELETE CASCADE,
  CONSTRAINT fk_itv_loc FOREIGN KEY (LOC_ID) REFERENCES LOCATION (LOC_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 10. FIT_CART_ITEM
DROP TABLE IF EXISTS FIT_CART_ITEM;
CREATE TABLE FIT_CART_ITEM (
  FIT_ITEM_ID VARCHAR(36) NOT NULL,
  FIT_CART_ID VARCHAR(36) NOT NULL,
  ITV_SKUID VARCHAR(50) NOT NULL,
  PRIMARY KEY (FIT_ITEM_ID),
  INDEX idx_fci_cart (FIT_CART_ID),
  INDEX idx_fci_skuid (ITV_SKUID),
  CONSTRAINT fk_fci_cart FOREIGN KEY (FIT_CART_ID) REFERENCES FIT_CART (FIT_CART_ID) ON DELETE CASCADE,
  CONSTRAINT fk_fci_sku FOREIGN KEY (ITV_SKUID) REFERENCES ITEM_VARIANT (ITV_SKUID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 11. PAY_CART_ITEM
DROP TABLE IF EXISTS PAY_CART_ITEM;
CREATE TABLE PAY_CART_ITEM (
  PAY_ITEM_ID VARCHAR(36) NOT NULL,
  PAY_CART_ID VARCHAR(36) NOT NULL,
  ITV_SKUID VARCHAR(50) NOT NULL,
  QTY INT NOT NULL DEFAULT 1,
  PRIMARY KEY (PAY_ITEM_ID),
  INDEX idx_pci_cart (PAY_CART_ID),
  INDEX idx_pci_skuid (ITV_SKUID),
  CONSTRAINT fk_pci_cart FOREIGN KEY (PAY_CART_ID) REFERENCES PAY_CART (PAY_CART_ID) ON DELETE CASCADE,
  CONSTRAINT fk_pci_sku FOREIGN KEY (ITV_SKUID) REFERENCES ITEM_VARIANT (ITV_SKUID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 12. FITTING_ROOM_ORDER
DROP TABLE IF EXISTS FITTING_ROOM_ORDER;
CREATE TABLE FITTING_ROOM_ORDER (
  FTR_ORD_ID VARCHAR(36) NOT NULL,
  FTS_ID VARCHAR(36) NOT NULL,
  ITV_SKUID VARCHAR(50) NOT NULL,
  EMP_ID VARCHAR(36) NULL,
  FTR_ORD_Status VARCHAR(50) NOT NULL DEFAULT 'pending',
  FTR_ORD_DateTime DATETIME NOT NULL,
  PRIMARY KEY (FTR_ORD_ID),
  INDEX idx_fro_session (FTS_ID),
  INDEX idx_fro_sku (ITV_SKUID),
  INDEX idx_fro_emp (EMP_ID),
  CONSTRAINT fk_fro_session FOREIGN KEY (FTS_ID) REFERENCES FITTING_SESSION (FTS_ID) ON DELETE CASCADE,
  CONSTRAINT fk_fro_sku FOREIGN KEY (ITV_SKUID) REFERENCES ITEM_VARIANT (ITV_SKUID) ON DELETE CASCADE,
  CONSTRAINT fk_fro_emp FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 13. SALE_ORDER
DROP TABLE IF EXISTS SALE_ORDER;
CREATE TABLE SALE_ORDER (
  ORD_ID VARCHAR(36) NOT NULL,
  CUS_ID VARCHAR(36) NULL,
  EMP_ID VARCHAR(36) NULL,
  ORD_Method VARCHAR(50) NOT NULL,
  ORD_Channel VARCHAR(50) NOT NULL,
  ORD_DateTime DATETIME NOT NULL,
  ORD_Total DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (ORD_ID),
  INDEX idx_so_cus (CUS_ID),
  INDEX idx_so_emp (EMP_ID),
  CONSTRAINT fk_so_cus FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER (CUS_ID) ON DELETE SET NULL,
  CONSTRAINT fk_so_emp FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 14. SALE_ORDER_LINE
DROP TABLE IF EXISTS SALE_ORDER_LINE;
CREATE TABLE SALE_ORDER_LINE (
  ORD_LINE_ID VARCHAR(36) NOT NULL,
  ORD_ID VARCHAR(36) NOT NULL,
  ITV_SKUID VARCHAR(50) NOT NULL,
  ORD_LINE_UPrice DECIMAL(10,2) NOT NULL,
  ORD_LINE_Qty INT NOT NULL,
  PRIMARY KEY (ORD_LINE_ID),
  INDEX idx_sol_order (ORD_ID),
  INDEX idx_sol_sku (ITV_SKUID),
  CONSTRAINT fk_sol_order FOREIGN KEY (ORD_ID) REFERENCES SALE_ORDER (ORD_ID) ON DELETE CASCADE,
  CONSTRAINT fk_sol_sku FOREIGN KEY (ITV_SKUID) REFERENCES ITEM_VARIANT (ITV_SKUID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;
