-- ==========================================================
-- crwn.st SQLite Database Schema
-- Matches ER Diagram: ERD-070969
-- ==========================================================

PRAGMA foreign_keys = ON;

-- 1. CUSTOMER
CREATE TABLE IF NOT EXISTS CUSTOMER (
  CUS_ID VARCHAR(36) PRIMARY KEY,
  CUS_FName VARCHAR(100) NOT NULL,
  CUS_LName VARCHAR(100) NOT NULL,
  CUS_Email VARCHAR(150),
  CUS_Tel VARCHAR(20) UNIQUE NOT NULL,
  CUS_Pass VARCHAR(100)
);

-- 2. EMPLOYEE
CREATE TABLE IF NOT EXISTS EMPLOYEE (
  EMP_ID VARCHAR(36) PRIMARY KEY,
  EMP_FName VARCHAR(100) NOT NULL,
  EMP_LName VARCHAR(100) NOT NULL,
  EMP_Tel VARCHAR(20),
  EMP_Email VARCHAR(150),
  EMP_Pass VARCHAR(100) NOT NULL,
  EMP_Role VARCHAR(50) NOT NULL
);

-- 3. FITTING_ROOM
CREATE TABLE IF NOT EXISTS FITTING_ROOM (
  FTR_Num VARCHAR(20) PRIMARY KEY,
  FTR_Status VARCHAR(50) NOT NULL DEFAULT 'available'
);

-- 4. FITTING_SESSION
CREATE TABLE IF NOT EXISTS FITTING_SESSION (
  FTS_ID VARCHAR(36) PRIMARY KEY,
  FTR_NUM VARCHAR(20) NOT NULL,
  CUS_ID VARCHAR(36),
  FTS_DateTime TEXT NOT NULL,
  FOREIGN KEY (FTR_NUM) REFERENCES FITTING_ROOM(FTR_Num) ON DELETE CASCADE,
  FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID) ON DELETE SET NULL
);

-- 5. PAY_CART
CREATE TABLE IF NOT EXISTS PAY_CART (
  PAY_CART_ID VARCHAR(36) PRIMARY KEY,
  CUS_ID VARCHAR(36),
  FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID) ON DELETE SET NULL
);

-- 6. FIT_CART
CREATE TABLE IF NOT EXISTS FIT_CART (
  FIT_CART_ID VARCHAR(36) PRIMARY KEY,
  FTS_ID VARCHAR(36) NOT NULL,
  PAY_CART_ID VARCHAR(36),
  FOREIGN KEY (FTS_ID) REFERENCES FITTING_SESSION(FTS_ID) ON DELETE CASCADE,
  FOREIGN KEY (PAY_CART_ID) REFERENCES PAY_CART(PAY_CART_ID) ON DELETE SET NULL
);

-- 7. LOCATION
CREATE TABLE IF NOT EXISTS LOCATION (
  LOC_ID VARCHAR(36) PRIMARY KEY,
  LOC_Zone VARCHAR(50),
  LOC_Lock VARCHAR(50),
  LOC_Shelf VARCHAR(50),
  LOC_Label VARCHAR(100)
);

-- 8. ITEM
CREATE TABLE IF NOT EXISTS ITEM (
  ITM_ID VARCHAR(36) PRIMARY KEY,
  ITM_Name VARCHAR(150) NOT NULL,
  ITM_Description TEXT,
  ITM_Price REAL NOT NULL,
  ITM_Category VARCHAR(100),
  ITM_Tag VARCHAR(200),
  ITM_Image TEXT
);

-- 9. ITEM_VARIANT
CREATE TABLE IF NOT EXISTS ITEM_VARIANT (
  ITV_SKUID VARCHAR(50) PRIMARY KEY,
  ITM_ID VARCHAR(36) NOT NULL,
  ITV_Color VARCHAR(50),
  ITV_Size VARCHAR(20),
  ITV_Stock INTEGER NOT NULL DEFAULT 0,
  LOC_ID VARCHAR(36),
  FOREIGN KEY (ITM_ID) REFERENCES ITEM(ITM_ID) ON DELETE CASCADE,
  FOREIGN KEY (LOC_ID) REFERENCES LOCATION(LOC_ID) ON DELETE SET NULL
);

-- 10. FIT_CART_ITEM
CREATE TABLE IF NOT EXISTS FIT_CART_ITEM (
  FIT_ITEM_ID VARCHAR(36) PRIMARY KEY,
  FIT_CART_ID VARCHAR(36) NOT NULL,
  ITV_SKUID VARCHAR(50) NOT NULL,
  FOREIGN KEY (FIT_CART_ID) REFERENCES FIT_CART(FIT_CART_ID) ON DELETE CASCADE,
  FOREIGN KEY (ITV_SKUID) REFERENCES ITEM_VARIANT(ITV_SKUID) ON DELETE CASCADE
);

-- 11. PAY_CART_ITEM
CREATE TABLE IF NOT EXISTS PAY_CART_ITEM (
  PAY_ITEM_ID VARCHAR(36) PRIMARY KEY,
  PAY_CART_ID VARCHAR(36) NOT NULL,
  ITV_SKUID VARCHAR(50) NOT NULL,
  QTY INTEGER NOT NULL DEFAULT 1,
  FOREIGN KEY (PAY_CART_ID) REFERENCES PAY_CART(PAY_CART_ID) ON DELETE CASCADE,
  FOREIGN KEY (ITV_SKUID) REFERENCES ITEM_VARIANT(ITV_SKUID) ON DELETE CASCADE
);

-- 12. FITTING_ROOM_ORDER
CREATE TABLE IF NOT EXISTS FITTING_ROOM_ORDER (
  FTR_ORD_ID VARCHAR(36) PRIMARY KEY,
  FTS_ID VARCHAR(36) NOT NULL,
  ITV_SKUID VARCHAR(50) NOT NULL,
  EMP_ID VARCHAR(36),
  FTR_ORD_Status VARCHAR(50) NOT NULL DEFAULT 'pending',
  FTR_ORD_DateTime TEXT NOT NULL,
  FOREIGN KEY (FTS_ID) REFERENCES FITTING_SESSION(FTS_ID) ON DELETE CASCADE,
  FOREIGN KEY (ITV_SKUID) REFERENCES ITEM_VARIANT(ITV_SKUID) ON DELETE CASCADE,
  FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID) ON DELETE SET NULL
);

-- 13. SALE_ORDER
CREATE TABLE IF NOT EXISTS SALE_ORDER (
  ORD_ID VARCHAR(36) PRIMARY KEY,
  CUS_ID VARCHAR(36),
  EMP_ID VARCHAR(36),
  ORD_Method VARCHAR(50) NOT NULL,
  ORD_Channel VARCHAR(50) NOT NULL,
  ORD_DateTime TEXT NOT NULL,
  ORD_Total REAL NOT NULL,
  FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID) ON DELETE SET NULL,
  FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID) ON DELETE SET NULL
);

-- 14. SALE_ORDER_LINE
CREATE TABLE IF NOT EXISTS SALE_ORDER_LINE (
  ORD_LINE_ID VARCHAR(36) PRIMARY KEY,
  ORD_ID VARCHAR(36) NOT NULL,
  ITV_SKUID VARCHAR(50) NOT NULL,
  ORD_LINE_UPrice REAL NOT NULL,
  ORD_LINE_Qty INTEGER NOT NULL,
  FOREIGN KEY (ORD_ID) REFERENCES SALE_ORDER(ORD_ID) ON DELETE CASCADE,
  FOREIGN KEY (ITV_SKUID) REFERENCES ITEM_VARIANT(ITV_SKUID) ON DELETE CASCADE
);
