-- ==========================================================
-- crwn.st MySQL Database Schema (10 Tables)
-- Server: webdev.it.kmitl.ac.th / Database: s6807186
-- ==========================================================

-- ตารางข้อมูลหลัก

-- สร้างตารางพนักงาน
CREATE TABLE IF NOT EXISTS EMPLOYEE (
    EMP_ID VARCHAR(50) PRIMARY KEY,
    EMP_FName VARCHAR(100) NOT NULL,
    EMP_LName VARCHAR(100) NOT NULL,
    EMP_Tel VARCHAR(20),
    EMP_Email VARCHAR(100),
    EMP_Pass VARCHAR(255) NOT NULL,
    EMP_Role VARCHAR(50)
);

-- สร้างตารางลูกค้า
CREATE TABLE IF NOT EXISTS CUSTOMER (
    CUS_ID VARCHAR(50) PRIMARY KEY,
    CUS_FName VARCHAR(100) NOT NULL,
    CUS_LName VARCHAR(100) NOT NULL,
    CUS_Email VARCHAR(100),
    CUS_Tel VARCHAR(20),
    CUS_Pass VARCHAR(255) NOT NULL
);

-- สร้างตารางสินค้าหลัก
CREATE TABLE IF NOT EXISTS ITEM (
    ITM_ID VARCHAR(50) PRIMARY KEY,
    ITM_Name VARCHAR(255) NOT NULL,
    ITM_Description TEXT,
    ITM_Price DECIMAL(10, 2) NOT NULL,
    ITM_Category VARCHAR(100),
    ITM_Tag VARCHAR(100)
);

-- สร้างตารางตำแหน่งจัดเก็บ
CREATE TABLE IF NOT EXISTS LOCATION (
    LOC_ID VARCHAR(50) PRIMARY KEY,
    LOC_Zone VARCHAR(50),
    LOC_Lock VARCHAR(50),
    LOC_Shelf VARCHAR(50),
    LOC_Label VARCHAR(50)
);

-- ตารางข้อมูลย่อยและการทำรายการ

-- สร้างตารางสินค้าแยกย่อย (เช่น สี ไซส์)
CREATE TABLE IF NOT EXISTS ITEM_VARIANT (
    ITV_SKUID VARCHAR(50) PRIMARY KEY,
    ITM_ID VARCHAR(50),
    ITV_Color VARCHAR(50),
    ITV_Size VARCHAR(50),
    ITV_Stock INT DEFAULT 0,
    LOC_ID VARCHAR(50),
    FOREIGN KEY (ITM_ID) REFERENCES ITEM(ITM_ID),
    FOREIGN KEY (LOC_ID) REFERENCES LOCATION(LOC_ID)
);

-- สร้างตารางตะกร้าสินค้า
CREATE TABLE IF NOT EXISTS PAY_CART (
    PAY_CART_ID VARCHAR(50) PRIMARY KEY,
    CUS_ID VARCHAR(50),
    FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID)
);

-- สร้างตารางรายการในตะกร้าสินค้า
CREATE TABLE IF NOT EXISTS PAY_CART_ITEM (
    PAY_ITEM_ID VARCHAR(50) PRIMARY KEY,
    PAY_CART_ID VARCHAR(50),
    ITV_SKUID VARCHAR(50),
    FOREIGN KEY (PAY_CART_ID) REFERENCES PAY_CART(PAY_CART_ID),
    FOREIGN KEY (ITV_SKUID) REFERENCES ITEM_VARIANT(ITV_SKUID)
);

-- สร้างตารางคำสั่งซื้อ
CREATE TABLE IF NOT EXISTS SALE_ORDER (
    ORD_ID VARCHAR(50) PRIMARY KEY,
    CUS_ID VARCHAR(50),
    EMP_ID VARCHAR(50),
    ORD_Method VARCHAR(50),
    ORD_Channel VARCHAR(50),
    ORD_DateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    ORD_Total DECIMAL(12, 2) NOT NULL,
    FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
);

-- สร้างตารางรายละเอียดคำสั่งซื้อ
CREATE TABLE IF NOT EXISTS SALE_ORDER_LINE (
    ORD_LINE_ID VARCHAR(50) PRIMARY KEY,
    ORD_ID VARCHAR(50),
    ITV_SKUID VARCHAR(50),
    ORD_LINE_UPrice DECIMAL(10, 2) NOT NULL,
    ORD_LINE_Qty INT NOT NULL,
    FOREIGN KEY (ORD_ID) REFERENCES SALE_ORDER(ORD_ID),
    FOREIGN KEY (ITV_SKUID) REFERENCES ITEM_VARIANT(ITV_SKUID)
);

-- สร้างตารางการใช้ห้องลองเสื้อ
CREATE TABLE IF NOT EXISTS FITTING_ROOM (
    FTR_OrderID VARCHAR(50) PRIMARY KEY,
    ITV_SKUID VARCHAR(50),
    EMP_ID VARCHAR(50),
    FTR_Number VARCHAR(20) NOT NULL,
    FTR_OrderTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    FTR_FinishTime DATETIME,
    FOREIGN KEY (ITV_SKUID) REFERENCES ITEM_VARIANT(ITV_SKUID),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
);

-- ==========================================================
-- 7. Performance Optimization: Database Indexes
-- ==========================================================
CREATE INDEX idx_cus_tel ON CUSTOMER(CUS_Tel);
CREATE INDEX idx_item_variant_itm ON ITEM_VARIANT(ITM_ID);
CREATE INDEX idx_sale_order_cus ON SALE_ORDER(CUS_ID);
CREATE INDEX idx_sale_order_line_ord ON SALE_ORDER_LINE(ORD_ID);
